# Generated by Django 5.2.7 on 2025-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='approve_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='notification',
            name='reject_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
